SELECT DISTINCT PRO.NOMBRE AS NOMBRE, 
	   CITA.CODIGO AS CODIGO
	   FROM fac_p_profesional AS PRO, 
	   fac_p_rx_profcprod AS CENPRO, 
	   fac_m_citas AS CITA 
	   WHERE CENPRO.CODIGO = '1301' AND		
	   CENPRO.PROFESIONAL=PRO.CODIGO AND
	   CENPRO.PROFESIONAL=CITA.CODIGO AND
	   CITA.CODIGO=PRO.CODIGO AND
	   CITA.CENTROPROD IS NULL
	   AND CONVERT(DATE, FECHA) = '2016-07-08'
	   ORDER BY CITA.CODIGO