SELECT FECHA
,COUNT(CODIGO) AS CANTIDAD
FROM fac_m_citas
WHERE DAY(FECHA) = '08'
	   AND MONTH(FECHA) = '07'
	   AND YEAR(FECHA) = '2016'
AND CENTROPROD IS NULL
GROUP BY CODIGO, FECHA ORDER BY CODIGO